---
# Insert new cops alphabetically

require:
  - standard/cop/semantic_blocks

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*

Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['\A#']
