---
name: Lint Docs

on:
  push:
    branches:
      - master
    paths:
      - "*.md"
      - "**/*.md"
  pull_request:
    paths:
      - "*.md"
      - "**/*.md"

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Run Markdown linter
        run: |
          gem install mdl
          mdl README.md
  forspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Run Forspell
        run: |
          sudo apt-get install hunspell
          gem install forspell
          forspell *.md

  liche:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: Run liche
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u github.com/raviqqe/liche
          liche -x localhost README.md
